### ISSUE TITLE
Plugins `dll`s are missing in the repository

### ISSUE THREAD

**Issue by nathanpovo** [Jumprocks1/drum-game#3]
The plugins `bassopus`, `basswebm`, and `bassmidi` are missing from the repository. These plugins seem to be required by the application when playing with audio files (the issue is not present when using the YouTube websocket).

### To Reproduce

1. Clone repository
2. Ensure that `yt-dlp` is somewhere in the path
3. Build and run the `DrumGame.Desktop` project
4. Open a map that contains a reference to a YouTube video
5. When informed that the audio file is missing, select the "Download YouTube Audio" option
6. Toggle playback

### Expected Behaviour

Playback should use the local audio file without issues.

### Actual Behaviour

Playback does no longer works and errors are logged in the console about missing plugins

![image](https://github.com/user-attachments/assets/12041585-2859-44d8-8fb5-58bcd3e5cc2f)

### Workaround

Delete the directory and all the audio files in the directory `.\resources\temp\youtube` and use the YouTube websocket.

### Additional Context

I tried searching for these packages on `NuGet` but could not find them. I also tried downloading a compiled release and adding a reference to the plugin `dll`s but it does not work (the IDE complains of missing assembly metadata).

**Comment by nathanpovo** [comment]
I can see that the files are in the compiled release.
![image](https://github.com/user-attachments/assets/c0a3238d-b06b-4f87-bc18-bc292da32795)

Which, I assume, means that they can be distributed within the repository itself.

Can these files be added to `DrumGame.Desktop` project in the repository as regular files that are copied on build?
![image](https://github.com/user-attachments/assets/0bef799b-8cf4-4bef-b15a-c15c1c832317)

**Comment by Jumprocks1** [comment]
Thank you for reporting this.

You are correct that I do not include those in the repository here. As you stated, they are included in the release builds. This is because I have a private repo has additional assets that I wasn't sure if they should be included in this public repo, but I think these would be fine to include.

For reference, they can all be downloaded here: https://www.un4seen.com/ (under add-ons). It's probably possible to have them included through NuGet as you mentioned ([ManagedBass.Midi](https://www.nuget.org/packages/ManagedBass.Midi), [ManagedBass.Opus](https://www.nuget.org/packages/ManagedBass.Opus)) though there's no package for the Webm add-on. [The framework](https://github.com/ppy/osu-framework) is including bassmix.dll, bass_fx.dll, and others through NuGet I believe, but I'm not sure how.

For now, I have added the dlls into this repo's [resources/lib](https://github.com/Jumprocks1/drum-game/tree/main/resources/lib) folder. That is where I store them on my local machine when developing. I also updated the README under [Running From Source](https://github.com/Jumprocks1/drum-game/blob/main/DrumGame/README.md#running-from-source).

Here's the commit for the changes https://github.com/Jumprocks1/drum-game/commit/4f2ccc9aed127dcb5acbe84ca079a5868598674d

In the future I will probably change it so that those dlls are in the `resources/lib` folder for releases instead of the main bin folder, that way if you share a resources folder between a release version and local development, it should work fine.

**Comment by nathanpovo** [comment]
Can confirm that the errors are no longer there with the `dll`s in `resources\lib`.

> It's probably possible to have them included through NuGet as you mentioned ([ManagedBass.Midi](https://www.nuget.org/packages/ManagedBass.Midi), [ManagedBass.Opus](https://www.nuget.org/packages/ManagedBass.Opus)) though there's no package for the Webm add-on.

Is this related to [the issue mentioned in the `README.md`](https://github.com/Jumprocks1/drum-game/blob/5ab61405709e4fc288e069a49d73d6c72912ca8a/DrumGame/README.md?plain=1#L6C166-L6C843)? I actually managed to work around that issue but I was still getting errors.

**Comment by nathanpovo** [comment]
Did some additional testing and I think I may have managed to solve the issue.

I will create a new issue to handle solving the references to the osu framework and then tackle this.

**Comment by nathanpovo** [comment]
> Did some additional testing and I think I may have managed to solve the issue.
> 
> I will create a new issue to handle solving the references to the osu framework and then tackle this.

Nevermind, still getting the errors.

**Comment by nathanpovo** [comment]
I'll close this issue since it has been addressed with commit 4f2ccc9aed127dcb5acbe84ca079a5868598674d and open another issue to handle the bass add-ons.
